name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        use: pacman -S make

      - name: Install
        run: |
          chmod +x ./install.sh
          ./install.sh

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gemu
          path: ./gemu
          retention-days: 5
