name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install
        run: |
          chmod +x ./install.sh
          ./install.sh

      - name: Upload chadwm artifact
        uses: actions/upload-artifact@v3
        with:
          name: chadwm
          path: ./suckless/chadwm/dwm
          retention-days: 5

      - name: Upload slstatus artifact
        uses: actions/upload-artifact@v3
        with:
          name: slstatus
          path: ./suckless/slstatus/slstatus
          retention-days: 5

      - name: Upload slock artifact
        uses: actions/upload-artifact@v3
        with:
          name: slock
          path: ./suckless/slock/slock
          retention-days: 5
